
%  MATLAB R2024b | Командыг өгөхөд шууд ажиллана
%  Зүүн:  UMa — SNR vs M (line+marker)
%  Баруун: InH — Coverage Ratio vs M (bar chart)
 
clc; clear; close all;
 
%% ── Слайдын яг утгууд ─────────────────────────────────────
 
% Зүүн график — UMa: SNR vs M
M_vals   = [32,  64, 128, 256, 512, 1024];
SNR_vals = [ 0,   5,  11,  16,  21,   25];   % дБ
 
% Баруун график — InH: Coverage Ratio vs M
xlbl_InH = {'RIS-гүй','M=64','M=128','M=256'};
cov_vals  = [35, 79, 95, 100];               % %
 
%% ══════════════════════════════════════════════════════════
figure('Name','UMa & InH', ...
       'Position',[100 100 1200 520], ...
       'Color','white');
 
%% ── ЗҮҮН: UMa SNR vs M ────────────────────────────────────
ax1 = subplot(1,2,1);
 
% Log scale-д plot хийхийн тулд x утгуудыг log-д дамжуулна
plot(log2(M_vals), SNR_vals, ...
     '-o', ...
     'Color',           [0.85 0.33 0.10], ...
     'LineWidth',        2.5, ...
     'MarkerSize',       9, ...
     'MarkerFaceColor', [0.85 0.33 0.10]);
hold on;
 
% Утгын шошго — тэнцүү зайтай харагдана
for i = 1:length(M_vals)
    text(log2(M_vals(i)), SNR_vals(i) + 1.5, ...
         num2str(SNR_vals(i)), ...
         'HorizontalAlignment', 'center', ...
         'FontSize',    11, ...
         'FontWeight',  'bold', ...
         'Color',       [0.85 0.33 0.10]);
end
 
% X тэнхлэг: log2 дахь байршлуудыг M утгуудын шошгоор харуулна
set(ax1, ...
    'XTick',       log2(M_vals), ...
    'XTickLabel',  {'32','64','128','256','512','1024'}, ...
    'FontSize',    11, ...
    'Box',         'off', ...
    'YGrid',       'on', ...
    'GridAlpha',   0.4);
 
xlim([log2(25)  log2(1200)]);
ylim([0  30]);
yticks(0:5:30);
 
xlabel('M (RIS element)', 'FontSize', 13, 'FontWeight', 'bold');
ylabel('SNR (дБ)',         'FontSize', 13, 'FontWeight', 'bold');
title('Хотын гадна орчинд', ...
      'FontSize',   13, ...
      'FontWeight', 'bold', ...
      'Color',      [0.10 0.25 0.55]);
 
 
%% ── БАРУУН: InH Coverage Ratio vs M ──────────────────────
ax2 = subplot(1,2,2);
 
bar_clr = [0.44 0.50 0.72];
bar(1:4, cov_vals, 0.62, ...
    'FaceColor', bar_clr, ...
    'EdgeColor', 'none');
hold on;
 
for i = 1:4
    text(i, cov_vals(i)+2, num2str(cov_vals(i)), ...
         'HorizontalAlignment', 'center', ...
         'FontSize',    12, ...
         'FontWeight',  'bold', ...
         'Color',       [0.15 0.15 0.55]);
end
 
yline(99.7, '--g', 'LineWidth', 1.5, ...
    'Label', '99.7%', 'FontSize', 8, ...
    'LabelHorizontalAlignment', 'right');
 
set(ax2, 'XTick', 1:4, ...
    'XTickLabel', xlbl_InH, 'FontSize', 11);
ylabel('Coverage Ratio (%)', 'FontSize', 12, 'FontWeight', 'bold');
title('Дотор орчинд', ...
      'FontSize',   13, ...
      'FontWeight', 'bold', ...
      'Color',      [0.10 0.25 0.55]);
ylim([0 115]); grid on; box off;
 

sgtitle('5. Симуляцийн үр дүн  —  Слайд 14', ...
        'FontSize',   14, ...
        'FontWeight', 'bold', ...
        'Color',      [0.08 0.20 0.50]);