function createlegend(axes1)
%CREATELEGEND(axes1)
%  AXES1:  legend axes
 
%  Auto-generated by MATLAB on 28-May-2026 00:23:42
 
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southwest');
 
